sudo: required

services:
- docker

language: go

go:
- 1.16

env:
- GOFLAGS="-mod=readonly"

after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  make docker;
  fi
- if [[ -n "$TRAVIS_TAG" ]]; then
  make crossbuild release;
  fi
